import os

RABBITMQ_HOST = os.environ["RABBITMQ_HOST"]
RABBITMQ_PORT = os.environ["RABBITMQ_PORT"]

IMAGE_QUEUE = os.environ["IMAGE_QUEUE"]
IMAGE_EXCHANGE = os.environ["IMAGE_EXCHANGE"]
IMAGE_ROUTING_KEY = os.environ["IMAGE_ROUTING_KEY"]
