version: '3.8'

services:
    api:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: api
        command: uvicorn main:app --reload --host 0.0.0.0 --port 8000
        ports:
            - '8000:8000'
        volumes: 
            - .:/usr/src/api
        environment:
            - POSTGRES_DATABASE
            - POSTGRES_USERNAME
            - POSTGRES_PASSWORD
            - POSTGRES_HOST
            - POSTGRES_PORT
        depends_on:
            - postgresdb

    postgresdb:
        container_name: postgres
        image: postgres:15-alpine
        volumes: 
            - pgdata:/var/lib/postgresql/data
        ports:
            - '5435:5432'
        environment:
            - POSTGRES_USERNAME
            - POSTGRES_PASSWORD
            - POSTGRES_DATABASE

volumes:
    pgdata: