deps:
	pip3 install -r requirements.txt	
	pip3 install torch torchvision torchaudio --extra-index-url https://download.pytorch.org/whl/cpu

up:
	docker-compose up -d --build
down:
	docker-compose down
